name: 'Elastic Logs'
description: 'Send workflow logs to Elasticsearch'
author: 'Massimiliano PIppi'
inputs:
  repo-token:
    required: true
    description: 'GitHub token to access repo data'
  job-names:
    required: false
    description: 'Comma separated names of the jobs to collect logs from, defaults to all jobs'
runs:
  using: 'node12'
  main: 'dist/index.js'
