name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # Make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  # Make sure the action works on a clean machine without building.
  e2e:
    # disable for no elastic cloud account avail at the moment
    # if: github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'
    if: ${{ false }}
    runs-on: ubuntu-latest
    needs: build # Wait for the other job to finish so we have some logs to fetch.
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: elastic-logs
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          cloud-id: ${{ secrets.CLOUD_ID }}
          username: ${{ secrets.ES_USER }}
          password: ${{ secrets.ES_PASS }}
          job-names: build
